# Generated by Django 4.2.4 on 2023-08-10 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ELearning', '0005_tag_prereq_learning'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ELearning.course_details')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ELearning.signup')),
            ],
        ),
    ]
