# Generated by Django 4.2.4 on 2023-08-10 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ELearning', '0007_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='course_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ELearning.user_course'),
        ),
    ]
