# Generated by Django 4.2.4 on 2023-08-15 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ELearning', '0008_alter_payment_course_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ref_code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('discount', models.IntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ELearning.course_details')),
            ],
        ),
    ]
